dist: xenial
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - pwd && cd tests && mkdir -v build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
  - ./simple_pputil

# matrix:
#   include:
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - sourceline: "ppa:ubuntu-toolchain-r/test"
#           packages:
#             - g++-5
#       env:
#          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#     - os: linux
#       addons:
#         apt:
#           sources:
#             - sourceline: "ppa:ubuntu-toolchain-r/test"
#           packages:
#             - g++-6
#       env:
#         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

#     - os: linux
#       addons:
#         apt:
#           sources:
#             - sourceline: "ppa:ubuntu-toolchain-r/test"
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#      - os: linux
#       addons:
#         apt:
#           sources:
#             - sourceline: "ppa:ubuntu-toolchain-r/test"
#           packages:
#             - g++-8
#       env:
#         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

# before_install:
#   - eval "${MATRIX_EVAL}"

# # script:
# #   - pwd && cd tests && mkdir build && cd build
# #   - cmake -DCMAKE_BUILD_TYPE=Release ../
# #   - make
# #   - ./simple_pputil
